# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    disable_csrf_role: ROLE_API_USER
    param_fetcher_listener: true
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    exception:
        serializer_error_renderer: true
        enabled: true
    serializer:
        serialize_null: true
    format_listener:
        enabled: true
        rules:
            - { path: '^/', stop: true }
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
    view:
        view_response_listener: true
        mime_types:
            json: ['application/json', 'application/x-json', 'application/vnd.example-com.foo+json']
