jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: false
    handlers:
        datetime:
            default_format: "Y-m-d H:i:s"
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'
