# Read the documentation: https://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html
nelmio_api_doc:
    documentation:
        info:
            title: '%api.title%'
            description: '%api.description%'
            version: '%api.version%'
        security:
            - ApiKeyAuth: []
    areas:
        path_patterns:
            - ^/api
