# Read the documentation: https://symfony.com/doc/current/reference/configuration/web_profiler.html
web_profiler:
    toolbar: true
    intercept_redirects: false

framework:
    profiler:
        only_exceptions: false
